version: '3'

services:
  sandbox-nuxt-composition-api:
    container_name: sandbox-nuxt-composition-api
    image: sandbox-nuxt-composition-api:0.0.1
    build: .
    ports:
      - 3001:3000
    tty: true
    volumes:
      - ./:/app
    environment:
      - NUXT_TELEMETRY_DISABLED=1
    command: yarn dev
