version: '3'

services:
  ixdr-webfront-proto:
    container_name: sandbox-nuxt-composition-api
    image: sandbox-nuxt-composition-api0.0.1
    build: .
    ports:
      - 3001:3000
    tty: true
    volumes:
      - ./:/app
#    command: yarn local
